lib/diamondway_web/router.ex
defmodule DiamondwayWeb.Router do
  use DiamondwayWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DiamondwayWeb.Plugs.FetchUser
    plug DiamondwayWeb.Plugs.PublicIp
    plug DiamondwayWeb.Plugs.SetLocale
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug DiamondwayWeb.Plugs.FetchUser
    plug DiamondwayWeb.Plugs.RestrictAccess, :api
    plug DiamondwayWeb.Plugs.PublicIp
  end

  pipeline :public_api do
    plug DiamondwayWeb.Plugs.PublicIp
  end

  pipeline :admin do
    plug :browser
    plug DiamondwayWeb.Plugs.RestrictAccess
    plug DiamondwayWeb.Plugs.PublicIp
  end

  pages = [:venue, :faq]

  scope "/", DiamondwayWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/registration", RegistrationController, :new
    post "/registration", RegistrationController, :create
    get "/registration/success", RegistrationController, :success

    get "/check", RegistrationController, :check_status_form
    post "/check", RegistrationController, :check_status
    post "/resend_email", RegistrationController, :resend_email

    for page <- pages do
      get "/#{page}", PageController, page
    end

    get "/admin/login", SessionController, :new
    post "/admin/login", SessionController, :create
    get "/admin/logout", SessionController, :delete
  end

  if Mix.env() in [:dev, :staging] do
    scope "/dev" do
      pipe_through :browser

      get "/email/:type", DiamondwayWeb.EmailController, :preview

      forward("/graphiql", Absinthe.Plug.GraphiQL, schema: DiamondwayWeb.GraphQL.Schema)
      forward("/mailbox", Plug.Swoosh.MailboxPreview, base_path: "/dev/mailbox")
    end
  end

  scope "/api" do
    pipe_through :api

    forward "/", Absinthe.Plug, schema: DiamondwayWeb.GraphQL.Schema
  end

  scope "/admin", DiamondwayWeb do
    pipe_through :admin

    get "/*path", AdminController, :react, as: :admin_root
  end
end

lib/diamondway_web/views/layout_view.ex
defmodule DiamondwayWeb.LayoutView do
  use DiamondwayWeb, :view

  def html_tag(%Plug.Conn{} = conn) do
    case conn.assigns[:locale] do
      "zh" ->
        {:safe, ~s{<html lang=\"zh-Hant\">}}

      other ->
        {:safe, ~s{<html lang=\"#{other}\">}}
    end
  end
end

lib/diamondway_web/templates/layout/_head.html.eex
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Mahamudra Taipei 2020</title>
  <%= case assigns[:locale] do %>
    <% en when en in ["en", :en] -> %>
      <link rel="stylesheet" href="https://use.typekit.net/eip2xub.css">
    <% _ -> %>
      <link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC&display=swap" rel="stylesheet">
  <% end %>
  <link rel="stylesheet" href="<%= Routes.static_path(Endpoint, "/css/app.css") %>"/>
  <link rel="icon" href="<%= Routes.static_path(Endpoint, "/images/logo-solo.svg") %>" type="image/svg+xml"/>
</head>

lib/diamondway_web/templates/layout/_header.html.eex
<nav class="navbar" id="navbar">
  <div class="navbar__inner">
    <div id="hamburgerToggle">
      <input type="checkbox" />
      <span></span><span></span><span></span>
    </div>
    <div class="navbar__menu" id="offcanvas">
      <%= case assigns[:locale] do %>
        <% en when en in ["en", :en] -> %>
        <a class="navbar__item" href="/">Homepage</a>
        <%= link "Registration", to: Routes.registration_path(Endpoint, :new), class: "navbar__item" %>
        <a class="navbar__item" href="/faq">Travel info</a>
        <a class="navbar__item" href="/check">Check your status</a>
        <a class="navbar__item" lang="zh" href="/?locale=zh">中文版</a>
        <% _ -> %>
        <a class="navbar__item" href="/" lang="zh">主頁</a>
        <%= link "註冊 (英文)", to: Routes.registration_path(Endpoint, :new), class: "navbar__item", lang: "zh" %>
        <a class="navbar__item" href="/check" lang="zh">檢查註冊狀態</a>
        <a class="navbar__item" href="/?locale=en">English</a>
      <% end %>
    </div>
    <a href="/" class="navbar__sitename">mahamudra.taipei</a>
    <div class="navbar__right">
      <a class="navbar__logo" href="/">
        <%= img_tag Routes.static_path(Endpoint, "/images/logo-solo.svg"), class: "hide-on-desktop" %>
        <%= img_tag Routes.static_path(Endpoint, "/images/logo-desktop-white.svg"), class: "hide-on-mobile", id: "logo-white" %>
        <%= img_tag Routes.static_path(Endpoint, "/images/logo-desktop.svg"), class: "hide-on-mobile", id: "logo-opaque" %>
      </a>
    </div>
  </div>
</nav>

lib/diamondway_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Mahamudra Taipei 2020</title>
    <link rel="stylesheet" href="https://use.typekit.net/eip2xub.css">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/admin.css") %>"/>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/admin.js") %>"></script>
  </body>
</html>

lib/diamondway_web/templates/layout/app.html.eex
<!DOCTYPE html>
<%= html_tag(@conn) %>
  <%= render "_head.html", assigns %>
  <%= if assigns[:body_class] do %>
    <body class="<%= @body_class %>">
  <% else %>
    <body>
  <% end %>
    <%= render "_header.html", assigns %>
    <main role="main">
      <%= render "_flash.html", assigns %>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <%= render "_footer.html", assigns %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>